# Server configuration

server:
  port: 10005
  servlet:
    context-path: /doc-service

spring:
  application:
    name: doc-service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    root: info


