# Server configuration

server:
  port: 10005
  servlet:
    context-path: /doc-service

spring:
  application:
    name: DOC-UTILITY-SERVICE
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: pdf-group
#      auto-offset-reset: earliest
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: '*'
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: info