# Server configuration

server:
  port: 10005
  servlet:
    context-path: /doc-service

spring:
  application:
    name: doc-service
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
eureka:
  client:
    service-url:
      defaultZone: http://eureka.guardianservices.in:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: 80.225.218.113
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    root: info


